// Mock data for ALL event types (critical, behavioral, operational)
// Each monitor sees ALL these events from its vehicle group

export interface EventType {
  codigo: string;
  nome: string;
  categoria: 'critical' | 'behavioral' | 'operational';
  severidade_padrao: 'low' | 'medium' | 'high' | 'critical';
  icone: string;
  cor: string;
  tempo_resposta_segundos: number;
  descricao: string;
}

export interface Event {
  id: number;
  tipo_evento_codigo: string;
  tipo_evento_nome: string;
  categoria: 'critical' | 'behavioral' | 'operational';
  severidade: 'low' | 'medium' | 'high' | 'critical';
  device_id: string;
  nome_motorista?: string;
  timestamp: string;
  latitude: number;
  longitude: number;
  velocidade?: number;
  dados_adicionais: any;
  processado: boolean;
}

// Catálogo completo de 20 tipos de eventos
export const eventTypesCatalog: EventType[] = [
  // CRITICAL EVENTS (8)
  {
    codigo: 'panic_button',
    nome: 'Botão de Pânico',
    categoria: 'critical',
    severidade_padrao: 'critical',
    icone: '🆘',
    cor: '#dc2626',
    tempo_resposta_segundos: 10,
    descricao: 'Motorista acionou botão de emergência/SOS',
  },
  {
    codigo: 'geofence_exit',
    nome: 'Saída de Cerca Virtual',
    categoria: 'critical',
    severidade_padrao: 'high',
    icone: '🚧',
    cor: '#ea580c',
    tempo_resposta_segundos: 30,
    descricao: 'Veículo saiu de zona geográfica autorizada',
  },
  {
    codigo: 'geofence_entry',
    nome: 'Entrada em Cerca Virtual',
    categoria: 'critical',
    severidade_padrao: 'medium',
    icone: '📍',
    cor: '#f59e0b',
    tempo_resposta_segundos: 30,
    descricao: 'Veículo entrou em zona geográfica monitorada',
  },
  {
    codigo: 'tamper_detected',
    nome: 'Violação do Rastreador',
    categoria: 'critical',
    severidade_padrao: 'critical',
    icone: '⚠️',
    cor: '#dc2626',
    tempo_resposta_segundos: 15,
    descricao: 'Tentativa de remoção ou sabotagem do equipamento',
  },
  {
    codigo: 'theft_suspected',
    nome: 'Suspeita de Roubo',
    categoria: 'critical',
    severidade_padrao: 'critical',
    icone: '🚨',
    cor: '#991b1b',
    tempo_resposta_segundos: 10,
    descricao: 'Correlação de indicadores de furto/roubo',
  },
  {
    codigo: 'collision_detected',
    nome: 'Colisão Detectada',
    categoria: 'critical',
    severidade_padrao: 'critical',
    icone: '💥',
    cor: '#dc2626',
    tempo_resposta_segundos: 20,
    descricao: 'Acelerômetro detectou impacto súbito',
  },
  {
    codigo: 'towing_detected',
    nome: 'Reboque Detectado',
    categoria: 'critical',
    severidade_padrao: 'high',
    icone: '🚛',
    cor: '#ea580c',
    tempo_resposta_segundos: 30,
    descricao: 'Movimento sem ignição ligada',
  },
  {
    codigo: 'unusual_hours',
    nome: 'Movimentação Fora de Horário',
    categoria: 'critical',
    severidade_padrao: 'high',
    icone: '🌙',
    cor: '#f59e0b',
    tempo_resposta_segundos: 30,
    descricao: 'Veículo operando fora do horário autorizado',
  },

  // BEHAVIORAL EVENTS (10)
  {
    codigo: 'harsh_brake',
    nome: 'Frenagem Brusca',
    categoria: 'behavioral',
    severidade_padrao: 'medium',
    icone: '🛑',
    cor: '#f59e0b',
    tempo_resposta_segundos: 300,
    descricao: 'Desaceleração superior a 20 km/h em curto intervalo',
  },
  {
    codigo: 'harsh_accel',
    nome: 'Aceleração Brusca',
    categoria: 'behavioral',
    severidade_padrao: 'medium',
    icone: '⚡',
    cor: '#f59e0b',
    tempo_resposta_segundos: 300,
    descricao: 'Aceleração superior a 15 km/h em curto intervalo',
  },
  {
    codigo: 'speeding',
    nome: 'Excesso de Velocidade',
    categoria: 'behavioral',
    severidade_padrao: 'high',
    icone: '🏎️',
    cor: '#ea580c',
    tempo_resposta_segundos: 180,
    descricao: 'Velocidade acima do limite permitido',
  },
  {
    codigo: 'sharp_turn',
    nome: 'Curva Acentuada',
    categoria: 'behavioral',
    severidade_padrao: 'medium',
    icone: '↩️',
    cor: '#f59e0b',
    tempo_resposta_segundos: 300,
    descricao: 'Mudança de direção superior a 45° em alta velocidade',
  },
  {
    codigo: 'fatigue_suspected',
    nome: 'Fadiga Detectada',
    categoria: 'behavioral',
    severidade_padrao: 'high',
    icone: '😴',
    cor: '#ea580c',
    tempo_resposta_segundos: 180,
    descricao: 'Aumento de micro-correções indicando cansaço',
  },
  {
    codigo: 'distracted_driving',
    nome: 'Direção Distraída',
    categoria: 'behavioral',
    severidade_padrao: 'medium',
    icone: '📱',
    cor: '#f59e0b',
    tempo_resposta_segundos: 300,
    descricao: 'Padrões erráticos de velocidade e direção',
  },
  {
    codigo: 'aggressive_driving',
    nome: 'Condução Agressiva',
    categoria: 'behavioral',
    severidade_padrao: 'high',
    icone: '😡',
    cor: '#ea580c',
    tempo_resposta_segundos: 180,
    descricao: 'Score fuzzy abaixo de 50 (classificação AGRESSIVO)',
  },
  {
    codigo: 'excessive_idle',
    nome: 'Ralenti Excessivo',
    categoria: 'behavioral',
    severidade_padrao: 'medium',
    icone: '⏱️',
    cor: '#f59e0b',
    tempo_resposta_segundos: 300,
    descricao: 'Motor ligado sem movimento por mais de 15 minutos',
  },
  {
    codigo: 'route_deviation',
    nome: 'Desvio de Rota',
    categoria: 'behavioral',
    severidade_padrao: 'medium',
    icone: '🗺️',
    cor: '#f59e0b',
    tempo_resposta_segundos: 60,
    descricao: 'Veículo fora da rota planejada',
  },
  {
    codigo: 'low_battery',
    nome: 'Bateria Baixa',
    categoria: 'behavioral',
    severidade_padrao: 'medium',
    icone: '🔋',
    cor: '#f59e0b',
    tempo_resposta_segundos: 900,
    descricao: 'Bateria do rastreador abaixo de 20%',
  },

  // OPERATIONAL EVENTS (2)
  {
    codigo: 'fuel_waste_detected',
    nome: 'Desperdício de Combustível',
    categoria: 'operational',
    severidade_padrao: 'low',
    icone: '⛽',
    cor: '#84cc16',
    tempo_resposta_segundos: 3600,
    descricao: 'Consumo acima do esperado para a rota',
  },
  {
    codigo: 'maintenance_due',
    nome: 'Manutenção Programada',
    categoria: 'operational',
    severidade_padrao: 'low',
    icone: '🔧',
    cor: '#84cc16',
    tempo_resposta_segundos: 86400,
    descricao: 'Veículo atingiu km ou prazo para manutenção',
  },
];

// Mock de eventos recentes (últimas 2 horas)
export const mockEvents: Event[] = [
  // Monitor 1 - Segurança (veículos críticos)
  {
    id: 1001,
    tipo_evento_codigo: 'harsh_brake',
    tipo_evento_nome: 'Frenagem Brusca',
    categoria: 'behavioral',
    severidade: 'high',
    device_id: 'USR-2001',
    nome_motorista: 'João Silva',
    timestamp: '2026-02-10T13:58:00',
    latitude: -23.5505,
    longitude: -46.6333,
    velocidade: 78,
    dados_adicionais: { desaceleracao_kmh: 32, tempo_segundos: 2.1 },
    processado: false,
  },
  {
    id: 1002,
    tipo_evento_codigo: 'speeding',
    tipo_evento_nome: 'Excesso de Velocidade',
    categoria: 'behavioral',
    severidade: 'high',
    device_id: 'USR-2001',
    nome_motorista: 'João Silva',
    timestamp: '2026-02-10T13:55:00',
    latitude: -23.5487,
    longitude: -46.6312,
    velocidade: 94,
    dados_adicionais: { limite: 60, excesso: 34 },
    processado: false,
  },
  {
    id: 1003,
    tipo_evento_codigo: 'harsh_accel',
    tipo_evento_nome: 'Aceleração Brusca',
    categoria: 'behavioral',
    severidade: 'medium',
    device_id: 'USR-2001',
    nome_motorista: 'João Silva',
    timestamp: '2026-02-10T13:52:00',
    latitude: -23.5465,
    longitude: -46.6289,
    velocidade: 42,
    dados_adicionais: { aceleracao_kmh: 28, tempo_segundos: 3.5 },
    processado: true,
  },
  {
    id: 1004,
    tipo_evento_codigo: 'aggressive_driving',
    tipo_evento_nome: 'Condução Agressiva',
    categoria: 'behavioral',
    severidade: 'critical',
    device_id: 'USR-2001',
    nome_motorista: 'João Silva',
    timestamp: '2026-02-10T13:42:00',
    latitude: -23.5505,
    longitude: -46.6333,
    velocidade: 65,
    dados_adicionais: { score_fuzzy: 48.2, perfil: 'AGRESSIVO', eventos_ultima_hora: 12 },
    processado: false,
  },

  {
    id: 1005,
    tipo_evento_codigo: 'speeding',
    tipo_evento_nome: 'Excesso de Velocidade',
    categoria: 'behavioral',
    severidade: 'high',
    device_id: 'SIM-1007',
    timestamp: '2026-02-10T13:48:00',
    latitude: -23.5273,
    longitude: -46.6658,
    velocidade: 112,
    dados_adicionais: { limite: 90, excesso: 22 },
    processado: true,
  },
  {
    id: 1006,
    tipo_evento_codigo: 'speeding',
    tipo_evento_nome: 'Excesso de Velocidade',
    categoria: 'behavioral',
    severidade: 'high',
    device_id: 'SIM-1007',
    timestamp: '2026-02-10T13:44:00',
    latitude: -23.5251,
    longitude: -46.6642,
    velocidade: 107,
    dados_adicionais: { limite: 90, excesso: 17 },
    processado: true,
  },

  {
    id: 1007,
    tipo_evento_codigo: 'collision_detected',
    tipo_evento_nome: 'Colisão Detectada',
    categoria: 'critical',
    severidade: 'critical',
    device_id: 'SIM-1003',
    timestamp: '2026-02-10T13:35:00',
    latitude: -23.6321,
    longitude: -46.5654,
    velocidade: 23,
    dados_adicionais: { impacto_g: 4.2, eixo: 'frontal' },
    processado: false,
  },
  {
    id: 1008,
    tipo_evento_codigo: 'harsh_brake',
    tipo_evento_nome: 'Frenagem Brusca',
    categoria: 'behavioral',
    severidade: 'high',
    device_id: 'SIM-1003',
    timestamp: '2026-02-10T13:33:00',
    latitude: -23.6315,
    longitude: -46.5648,
    velocidade: 82,
    dados_adicionais: { desaceleracao_kmh: 45, tempo_segundos: 2.8 },
    processado: true,
  },

  // Monitor 2 - Eficiência
  {
    id: 2001,
    tipo_evento_codigo: 'excessive_idle',
    tipo_evento_nome: 'Ralenti Excessivo',
    categoria: 'behavioral',
    severidade: 'medium',
    device_id: 'USR-3001',
    nome_motorista: 'Carlos Mendes',
    timestamp: '2026-02-10T13:20:00',
    latitude: -23.6145,
    longitude: -46.6987,
    velocidade: 0,
    dados_adicionais: { tempo_minutos: 28, combustivel_desperdicado_l: 0.35 },
    processado: true,
  },
  {
    id: 2002,
    tipo_evento_codigo: 'harsh_accel',
    tipo_evento_nome: 'Aceleração Brusca',
    categoria: 'behavioral',
    severidade: 'medium',
    device_id: 'USR-3001',
    nome_motorista: 'Carlos Mendes',
    timestamp: '2026-02-10T12:58:00',
    latitude: -23.6132,
    longitude: -46.6954,
    velocidade: 38,
    dados_adicionais: { aceleracao_kmh: 22, tempo_segundos: 2.9 },
    processado: true,
  },
  {
    id: 2003,
    tipo_evento_codigo: 'fuel_waste_detected',
    tipo_evento_nome: 'Desperdício de Combustível',
    categoria: 'operational',
    severidade: 'low',
    device_id: 'USR-3001',
    nome_motorista: 'Carlos Mendes',
    timestamp: '2026-02-10T12:30:00',
    latitude: -23.6098,
    longitude: -46.6921,
    velocidade: 42,
    dados_adicionais: { consumo_km_l: 6.2, esperado_km_l: 8.5, excesso_percent: 22 },
    processado: true,
  },

  {
    id: 2004,
    tipo_evento_codigo: 'excessive_idle',
    tipo_evento_nome: 'Ralenti Excessivo',
    categoria: 'behavioral',
    severidade: 'medium',
    device_id: 'SIM-2002',
    timestamp: '2026-02-10T14:10:00',
    latitude: -23.4987,
    longitude: -46.7123,
    velocidade: 0,
    dados_adicionais: { tempo_minutos: 47, combustivel_desperdicado_l: 0.59 },
    processado: false,
  },

  // Monitor 3 - Fadiga
  {
    id: 3001,
    tipo_evento_codigo: 'fatigue_suspected',
    tipo_evento_nome: 'Fadiga Detectada',
    categoria: 'behavioral',
    severidade: 'high',
    device_id: 'USR-4004',
    nome_motorista: 'Juliana Campos',
    timestamp: '2026-02-10T11:45:00',
    latitude: -23.2129,
    longitude: -45.8989,
    velocidade: 87,
    dados_adicionais: { micro_correcoes_30min: 8, baseline: 2, tempo_conducao_min: 270 },
    processado: true,
  },
  {
    id: 3002,
    tipo_evento_codigo: 'sharp_turn',
    tipo_evento_nome: 'Curva Acentuada',
    categoria: 'behavioral',
    severidade: 'low',
    device_id: 'USR-4004',
    nome_motorista: 'Juliana Campos',
    timestamp: '2026-02-10T11:42:00',
    latitude: -23.2118,
    longitude: -45.8965,
    velocidade: 62,
    dados_adicionais: { mudanca_direcao_graus: 52, velocidade_curva: 62 },
    processado: true,
  },

  // Monitor 4 - Conformidade
  {
    id: 4001,
    tipo_evento_codigo: 'speeding',
    tipo_evento_nome: 'Excesso de Velocidade',
    categoria: 'behavioral',
    severidade: 'high',
    device_id: 'SIM-3004',
    timestamp: '2026-02-10T13:55:00',
    latitude: -23.1823,
    longitude: -46.8843,
    velocidade: 118,
    dados_adicionais: { limite: 110, excesso: 8, limite_corporativo: 110, violacao_politica: true },
    processado: false,
  },
  {
    id: 4002,
    tipo_evento_codigo: 'speeding',
    tipo_evento_nome: 'Excesso de Velocidade',
    categoria: 'behavioral',
    severidade: 'high',
    device_id: 'SIM-3004',
    timestamp: '2026-02-10T13:42:00',
    latitude: -23.1789,
    longitude: -46.8821,
    velocidade: 122,
    dados_adicionais: { limite: 110, excesso: 12, limite_corporativo: 110, violacao_politica: true },
    processado: true,
  },

  // Eventos críticos diversos
  {
    id: 5001,
    tipo_evento_codigo: 'geofence_exit',
    tipo_evento_nome: 'Saída de Cerca Virtual',
    categoria: 'critical',
    severidade: 'high',
    device_id: 'SIM-1005',
    timestamp: '2026-02-10T12:15:00',
    latitude: -23.7123,
    longitude: -46.5432,
    velocidade: 54,
    dados_adicionais: { zona: 'Área Autorizada SP Sul', tipo: 'saida' },
    processado: true,
  },
  {
    id: 5002,
    tipo_evento_codigo: 'unusual_hours',
    tipo_evento_nome: 'Movimentação Fora de Horário',
    categoria: 'critical',
    severidade: 'high',
    device_id: 'SIM-3007',
    timestamp: '2026-02-10T03:42:00',
    latitude: -23.5687,
    longitude: -46.6234,
    velocidade: 38,
    dados_adicionais: { horario_permitido: '06:00-22:00', horario_evento: '03:42' },
    processado: true,
  },
  {
    id: 5003,
    tipo_evento_codigo: 'low_battery',
    tipo_evento_nome: 'Bateria Baixa',
    categoria: 'behavioral',
    severidade: 'medium',
    device_id: 'SIM-2004',
    timestamp: '2026-02-10T10:30:00',
    latitude: -23.4532,
    longitude: -46.7321,
    velocidade: 0,
    dados_adicionais: { nivel_bateria_percent: 18, voltagem: 3.42 },
    processado: true,
  },
  {
    id: 5004,
    tipo_evento_codigo: 'maintenance_due',
    tipo_evento_nome: 'Manutenção Programada',
    categoria: 'operational',
    severidade: 'low',
    device_id: 'SIM-1002',
    timestamp: '2026-02-10T08:00:00',
    latitude: -23.5234,
    longitude: -46.6543,
    velocidade: 0,
    dados_adicionais: { tipo: 'revisao_10000km', km_atual: 10087, km_prevista: 10000 },
    processado: true,
  },
];

// Estatísticas para dashboard
export const mockEventStats = {
  total_eventos_hoje: 142,
  criticos: 8,
  comportamentais: 118,
  operacionais: 16,
  nao_processados: 6,
  eventos_por_hora: [
    { hora: '08:00', total: 12 },
    { hora: '09:00', total: 18 },
    { hora: '10:00', total: 24 },
    { hora: '11:00', total: 15 },
    { hora: '12:00', total: 22 },
    { hora: '13:00', total: 35 },
    { hora: '14:00', total: 16 },
  ],
  top_tipos: [
    { tipo: 'harsh_brake', count: 32 },
    { tipo: 'speeding', count: 28 },
    { tipo: 'harsh_accel', count: 24 },
    { tipo: 'sharp_turn', count: 18 },
    { tipo: 'excessive_idle', count: 14 },
  ],
};
