// Mock data for Alerts generated by AI Monitors

export interface Alert {
  id: number;
  monitor_id: number;
  monitor_nome: string;
  veiculomonitor_id: number;
  device_id: string;
  nome_motorista?: string;
  titulo: string;
  mensagem: string;
  severidade: 'low' | 'medium' | 'high' | 'critical';
  tipo: 'behavior' | 'safety' | 'efficiency' | 'compliance' | 'prediction';
  criado_em: string;
  status: 'pending' | 'acknowledged' | 'resolved' | 'dismissed';
  reconhecido_em?: string;
  reconhecido_por?: string;
  eventos_relacionados: number; // count
  localizacao_lat?: number;
  localizacao_lon?: number;
  llm_analise_resumo: string;
  recomendacoes: string[];
}

export const mockAlerts: Alert[] = [
  {
    id: 1,
    monitor_id: 1,
    monitor_nome: 'Monitor de Segurança Frota Principal',
    veiculomonitor_id: 7,
    device_id: 'USR-2001',
    nome_motorista: 'João Silva',
    titulo: 'Padrão de Direção Agressiva Detectado',
    mensagem: 'Motorista João Silva apresentou 42 eventos comportamentais nas últimas 6 horas, incluindo 12 frenagens bruscas, 8 acelerações violentas e 3 violações de velocidade. Score atual: 48.2/100 (AGRESSIVO). Risco elevado de acidente.',
    severidade: 'critical',
    tipo: 'safety',
    criado_em: '2026-02-10T13:42:00',
    status: 'pending',
    eventos_relacionados: 42,
    localizacao_lat: -23.5505,
    localizacao_lon: -46.6333,
    llm_analise_resumo: 'Análise da IA identificou padrão consistente de direção agressiva com deterioração progressiva do score de 65 para 48 nas últimas 3 horas. Correlação alta entre violações de velocidade e frenagens bruscas subsequentes, indicando antecipação deficiente. Recomenda-se intervenção imediata.',
    recomendacoes: [
      'Contatar motorista imediatamente e orientar pausa de 30 minutos',
      'Agendar treinamento de direção defensiva',
      'Monitorar score nas próximas 48h - considerar afastamento se não melhorar',
      'Avaliar condições da rota atual (possível congestionamento gerando estresse)',
    ],
  },
  {
    id: 2,
    monitor_id: 1,
    monitor_nome: 'Monitor de Segurança Frota Principal',
    veiculomonitor_id: 12,
    device_id: 'SIM-1007',
    titulo: 'Múltiplas Violações de Velocidade em Zona Urbana',
    mensagem: 'Veículo SIM-1007 registrou 15 eventos de excesso de velocidade na Marginal Tietê, com pico de 112 km/h (limite 90 km/h). Score: 52.6/100.',
    severidade: 'high',
    tipo: 'compliance',
    criado_em: '2026-02-10T13:15:00',
    status: 'acknowledged',
    reconhecido_em: '2026-02-10T13:20:00',
    reconhecido_por: 'Gestor Maria',
    eventos_relacionados: 15,
    localizacao_lat: -23.5273,
    localizacao_lon: -46.6658,
    llm_analise_resumo: 'Veículo excedeu sistematicamente limite de velocidade em trechos com fiscalização eletrônica. Risco de multas (R$ 880/infração, 7 pontos CNH) e aumento de prêmio de seguro. Comportamento iniciou após troca de turno às 13h.',
    recomendacoes: [
      'Verificar se motorista está ciente dos limites de velocidade da rota',
      'Configurar alerta sonoro no rastreador para velocidades acima de 85 km/h',
      'Revisar metas de tempo de entrega - podem estar incentivando excesso de velocidade',
    ],
  },
  {
    id: 3,
    monitor_id: 2,
    monitor_nome: 'Monitor de Eficiência Combustível',
    veiculomonitor_id: 17,
    device_id: 'USR-3001',
    nome_motorista: 'Carlos Mendes',
    titulo: 'Alto Consumo de Combustível por Estilo de Condução',
    mensagem: 'Motorista Carlos Mendes apresentou 38 eventos de aceleração/frenagem brusca hoje, resultando em consumo estimado 22% acima da média da frota. Custo adicional estimado: R$ 180/dia.',
    severidade: 'medium',
    tipo: 'efficiency',
    criado_em: '2026-02-10T12:30:00',
    status: 'resolved',
    reconhecido_em: '2026-02-10T12:35:00',
    reconhecido_por: 'Supervisor João',
    eventos_relacionados: 38,
    localizacao_lat: -23.6145,
    localizacao_lon: -46.6987,
    llm_analise_resumo: 'Padrão de "jack-rabbit starts" (arrancadas bruscas) seguidas de frenagens pesadas. Análise de telemetria mostra pouco uso de freio motor. Rota inclui 47 semáforos, com possibilidade de otimização através de condução antecipatória.',
    recomendacoes: [
      'Enviar vídeo educativo sobre técnicas de eco-condução',
      'Configurar meta de redução de 15% em eventos de aceleração brusca',
      'Considerar bônus mensal por economia de combustível',
      'Avaliar troca para veículo híbrido nesta rota urbana',
    ],
  },
  {
    id: 4,
    monitor_id: 3,
    monitor_nome: 'Monitor de Fadiga - Motoristas Rodoviários',
    veiculomonitor_id: 24,
    device_id: 'USR-4004',
    nome_motorista: 'Juliana Campos',
    titulo: 'Sinais de Fadiga Detectados',
    mensagem: 'Motorista Juliana Campos apresenta aumento de 180% em micro-correções de direção nas últimas 2 horas. Score decresceu de 82 para 68. Conduzindo há 4h30min sem pausa.',
    severidade: 'high',
    tipo: 'safety',
    criado_em: '2026-02-10T11:45:00',
    status: 'resolved',
    reconhecido_em: '2026-02-10T11:50:00',
    reconhecido_por: 'Central Operações',
    eventos_relacionados: 16,
    localizacao_lat: -23.2129,
    localizacao_lon: -45.8989,
    llm_analise_resumo: 'Análise temporal mostra degradação progressiva: eventos/30min foram 2 → 4 → 6 → 8. Padrão consistente com fadiga segundo literatura (aumento de pequenas correções de direção, variação de velocidade). Motorista está 30 minutos além do intervalo recomendado.',
    recomendacoes: [
      'Orientar parada imediata em próximo posto (12 km à frente)',
      'Pausa mínima de 20 minutos com alongamento',
      'Revisar escala - considerar revezamento em viagens > 4h',
      'Implementar alertas automáticos aos gestores após 4h de condução contínua',
    ],
  },
  {
    id: 5,
    monitor_id: 4,
    monitor_nome: 'Monitor de Conformidade - Velocidade Máxima',
    veiculomonitor_id: 35,
    device_id: 'SIM-3004',
    titulo: 'Violações Recorrentes de Política de Velocidade Corporativa',
    mensagem: 'Veículo SIM-3004 violou política interna (máx 110 km/h em rodovias) em 11 ocasiões hoje. Score: 55.1/100. Terceira ocorrência esta semana.',
    severidade: 'high',
    tipo: 'compliance',
    criado_em: '2026-02-10T10:20:00',
    status: 'acknowledged',
    reconhecido_em: '2026-02-10T10:25:00',
    reconhecido_por: 'RH Compliance',
    eventos_relacionados: 11,
    localizacao_lat: -23.1823,
    localizacao_lon: -46.8843,
    llm_analise_resumo: 'Violações consistentes de política corporativa. Histórico mostra recorrência em 3 dias da semana passada. Motorista já foi orientado verbalmente em 07/02. Risco de responsabilização corporativa em caso de sinistro.',
    recomendacoes: [
      'Aplicar advertência formal conforme política de RH',
      'Configurar limitador eletrônico de velocidade em 115 km/h',
      'Exigir assinatura de termo de compromisso',
      'Próxima violação: suspensão temporária',
    ],
  },
  {
    id: 6,
    monitor_id: 1,
    monitor_nome: 'Monitor de Segurança Frota Principal',
    veiculomonitor_id: 4,
    device_id: 'SIM-1003',
    titulo: 'Deterioração Rápida de Score de Condução',
    mensagem: 'Veículo SIM-1003 teve score reduzido de 78 para 54.8 em apenas 2 horas. 31 eventos registrados, incluindo 2 eventos críticos de possível colisão.',
    severidade: 'critical',
    tipo: 'safety',
    criado_em: '2026-02-10T09:30:00',
    status: 'pending',
    eventos_relacionados: 31,
    localizacao_lat: -23.6321,
    localizacao_lon: -46.5654,
    llm_analise_resumo: 'Mudança abrupta e atípica no padrão de condução. Análise cruzada com histórico do veículo indica comportamento fora da linha de base. Possíveis causas: motorista substituto não treinado, condição mecânica do veículo (freios), ou estresse/urgência.',
    recomendacoes: [
      'Verificar se motorista habitual está ao volante (possível substituição não autorizada)',
      'Inspeção mecânica urgente - verificar sistema de freios',
      'Contato imediato com motorista para avaliar condição física/emocional',
      'Considerar acionamento de supervisor de campo para avaliação presencial',
    ],
  },
  {
    id: 7,
    monitor_id: 2,
    monitor_nome: 'Monitor de Eficiência Combustível',
    veiculomonitor_id: 20,
    device_id: 'SIM-2002',
    titulo: 'Ralenti Excessivo Impactando Custos',
    mensagem: 'Veículo SIM-2002 permaneceu em ralenti por 3h47min hoje (42% do tempo operacional). Desperdício estimado: 4.5 litros (R$ 28.80).',
    severidade: 'medium',
    tipo: 'efficiency',
    criado_em: '2026-02-10T14:10:00',
    status: 'pending',
    eventos_relacionados: 8,
    localizacao_lat: -23.4987,
    localizacao_lon: -46.7123,
    llm_analise_resumo: 'Análise de paradas mostra: 6 paradas longas (>20min) com motor ligado. Localização indica pontos de carga/descarga. Projeção mensal: R$ 576 de desperdício só neste veículo.',
    recomendacoes: [
      'Orientar motorista a desligar motor em paradas > 3 minutos',
      'Avaliar necessidade de ar-condicionado estacionário ou refrigeração alternativa',
      'Considerar sensor de ralenti com alerta sonoro automático',
      'Implementar política de "motor desligado" em todas operações de carga',
    ],
  },
  {
    id: 8,
    monitor_id: 1,
    monitor_nome: 'Monitor de Segurança Frota Principal',
    veiculomonitor_id: 10,
    device_id: 'USR-2004',
    nome_motorista: 'Ana Paula',
    titulo: 'Eventos de Frenagem em Sequência - Possível Distração',
    mensagem: 'Motorista Ana Paula registrou 8 frenagens bruscas em intervalo de 15 minutos, todas em velocidade > 70 km/h. Score: 59.8/100. Padrão sugere desatenção.',
    severidade: 'high',
    tipo: 'safety',
    criado_em: '2026-02-10T08:50:00',
    status: 'dismissed',
    reconhecido_em: '2026-02-10T09:00:00',
    reconhecido_por: 'Supervisor Carlos',
    eventos_relacionados: 8,
    localizacao_lat: -23.5687,
    localizacao_lon: -46.6789,
    llm_analise_resumo: 'Atualização 09:00: Após contato, motorista relatou trânsito atípico devido a acidente na via. Câmera de bordo confirma paradas súbitas de fluxo. Alerta descartado.',
    recomendacoes: [
      'Nenhuma ação necessária - condição externa validada',
    ],
  },
];

// Statistics for dashboard
export const mockAlertStats = {
  total_alertas_ativos: 6, // pending + acknowledged
  criticos: 2,
  altos: 3,
  medios: 2,
  baixos: 0,
  reconhecidos_hoje: 5,
  resolvidos_hoje: 2,
  taxa_resolucao_24h: 0.67, // 67%
  tempo_medio_reconhecimento_min: 4.2,
};
